### ISSUE TITLE
ValueError: could not convert string to float: '20/05/20, 06:09'

### ISSUE THREAD

**Issue by Villelmo** [process-intelligence-solutions/pm4py#266]
I try to implement a simple learning regression 

`reggressor.fit(X_train, y_train)`

But i get the following error: 

```
File "/home/lulu/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py", line 673, in check_array
    array = np.asarray(array, order=order, dtype=dtype)
```

**Comment by fit-alessandro-berti** [comment]
Dear Villelmo, how could we respond to you, when no information about the nature of X_train, y_train and the detailed exception traceback is provided?

**Comment by Villelmo** [comment]
Traceback:
```
Traceback (most recent call last):

  File "/home/lulu/machineLearning/simpleregression.py", line 30, in <module>
    reggressor.fit(X_train, y_train)

  File "/home/lulu/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_base.py", line 518, in fit
    X, y = self._validate_data(X, y, accept_sparse=accept_sparse,

  File "/home/lulu/anaconda3/lib/python3.8/site-packages/sklearn/base.py", line 433, in _validate_data
    X, y = check_X_y(X, y, **check_params)

  File "/home/lulu/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)

  File "/home/lulu/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py", line 871, in check_X_y
    X = check_array(X, accept_sparse=accept_sparse,

  File "/home/lulu/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)

  File "/home/lulu/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py", line 673, in check_array
    array = np.asarray(array, order=order, dtype=dtype)

ValueError: could not convert string to float: '20/05/20, 06:09'
```


This is my code: 

```
# simple learning regression 
# Data preprocessing 
# Importing the libraries 
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd # import data sets and manage data sets

# Importing dataset
dataset = pd.read_csv('/home/lulu/Escritorio/logs_Ing.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 1].values


# Splitting the dataset into the training set and test set 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 1/3,random_state = 0)

# Feature scaling
"""from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler() 
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)"""

# Fitting simple linear regression to the training set
from sklearn.linear_model import LinearRegression
reggressor = LinearRegression()
#ValueError: could not convert string to float: '20/05/20, 06:09'
reggressor.fit(X_train, y_train)

# Producing the test set results 
y_pred = reggressor.predict(X_test)

# Visualizing the test set results 
"""plt.scatter(X_test, y_test, color='red')
plt.plot(X_train, reggressor.predict(X_test),color = 'blue')
plt.title('Salary vs Experience (Training set)')
plt.xlabel('Years of Experience')
plt.ylabel('Salary')
plt.show()"""

```

Dataset:

![Dataset](https://i.imgur.com/bZpxHP9.png)

**Comment by Villelmo** [comment]
> when no information about the nature of X_train, y_train

I don't understand this part.

**Comment by fit-alessandro-berti** [comment]
Dear Villelmo,

As the code that you are using is not directly using PM4Py, and you are trying to provide string features to a scikit learn classifier (which is not allowed), I invite you to consider the feature extraction methods included in PM4Py as in the documentation

One thing that is missing from your dataset in order to consider it a process mining dataset is the case identifier, so events are collected without any reference to a case. So at the moment you could not use the feature extraction methods in PM4Py.

Moreover, the format in which you record the timestamp is peculiar, and Pandas is not able to recognise it. I would change the dataset to have a more standard datetime format
