### ISSUE TITLE
Docker Installation: xdg-open

### ISSUE THREAD

**Issue by samtaylor54321** [process-intelligence-solutions/pm4py#281]
I've been trying to the example notebooks after following the Docker installation guide however I'm getting the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/pm4py-2.2.15-py3.9.egg/pm4py/vis.py", line 162, in view_dfg
  File "/usr/local/lib/python3.9/site-packages/pm4py-2.2.15-py3.9.egg/pm4py/visualization/dfg/visualizer.py", line 92, in view
  File "/usr/local/lib/python3.9/site-packages/pm4py-2.2.15-py3.9.egg/pm4py/visualization/common/gview.py", line 36, in view
  File "/usr/local/lib/python3.9/site-packages/graphviz/files.py", line 277, in view
    return self.render(filename=filename, directory=directory,
  File "/usr/local/lib/python3.9/site-packages/graphviz/files.py", line 247, in render
    self._view(rendered, self._format, quiet_view)
  File "/usr/local/lib/python3.9/site-packages/graphviz/files.py", line 295, in _view
    view_method(filepath, quiet=quiet)
  File "/usr/local/lib/python3.9/site-packages/graphviz/backend.py", line 398, in view_unixoid
    subprocess.Popen(cmd, **kwargs)
  File "/usr/local/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'xdg-open'

Are there some additional steps in the Docker installation guide which aren't covered in the documentation?

**Comment by samtaylor54321** [comment]
Forgot to include the code which generated 

>>> import pm4py
>>> event_log = pd.read_csv("data/sample_data.csv")
>>> num_events = len(event_log)
>>> num_cases = len(event_log.case_id.unique())
>>> event_log = pm4py.format_dataframe(event_log, case_id='case_id', activity_key='activity', timestamp_key='timestamp')
>>> print("Number of events: {}\nNumber of cases: {}".format(num_events, num_cases))
Number of events: 42
Number of cases: 6
>>> dfg, start_activities, end_activities = pm4py.discover_dfg(event_log)
>>> pm4py.view_dfg(dfg, start_activities, end_activities)

sample_data.csv is the same as the data here: https://github.com/pm4py/pm4py-core/blob/release/notebooks/1_event_data.ipynb

**Comment by fit-alessandro-berti** [comment]
Dear samtaylor, since you run inside docker, you do not have direct access to the graphical / Windows interface.

For the visualizations in such settings, you will need to store them (for example, pm4py.save_vis_dfg(dfg, start_activities, end_activities, "trial.png")  and then open the file "trial.png" outside of the Docker)

**Comment by samtaylor54321** [comment]
Amazing, thank you!
