### ISSUE TITLE
pm4py does not run on M1

### ISSUE THREAD

**Issue by joleaf** [process-intelligence-solutions/pm4py#324]
Hi there,

first of all, thank you so much for providing this insane Process Mining library!

I have the following issue on my mac mini with an M1 chip:
After installing pm4py with pip: 
`pip install pm4py`
and running
`python -c "import pm4py"`

I got this error message:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/user4711/temp/test2/venv/lib/python3.10/site-packages/pm4py/__init__.py", line 20, in <module>
    from pm4py import util, objects, statistics, algo, visualization
  File "/Users/user4711/temp/test2/venv/lib/python3.10/site-packages/pm4py/util/__init__.py", line 18, in <module>
    from pm4py.util import variants_util, lp, constants, points_subset, business_hours, regex, xes_constants, vis_utils, \
  File "/Users/user4711/temp/test2/venv/lib/python3.10/site-packages/pm4py/util/lp/__init__.py", line 17, in <module>
    from pm4py.util.lp import solver, util, variants
  File "/Users/user4711/temp/test2/venv/lib/python3.10/site-packages/pm4py/util/lp/solver.py", line 58, in <module>
    from pm4py.util.lp.variants import cvxopt_solver, cvxopt_solver_custom_align, cvxopt_solver_custom_align_ilp, \
  File "/Users/user4711/temp/test2/venv/lib/python3.10/site-packages/pm4py/util/lp/variants/cvxopt_solver.py", line 19, in <module>
    from cvxopt import matrix, solvers
  File "/Users/user4711/temp/test2/venv/lib/python3.10/site-packages/cvxopt/__init__.py", line 50, in <module>
    import cvxopt.base
ImportError: dlopen(/Users/user4711/temp/test2/venv/lib/python3.10/site-packages/cvxopt/base.cpython-310-darwin.so, 0x0002): tried: '/Users/user4711/temp/test2/venv/lib/python3.10/site-packages/cvxopt/base.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
```

It seems to be an issue with the arm architecture and the cvxopt package. So I tried to compile cvxopt by myself:
https://cvxopt.org/install/index.html#macos
and ended with further issues like these:
https://github.com/cvxopt/cvxopt/issues/78#issuecomment-1050528754

Does anyone get pm4py working on an M1 Mac?

Thank you and best regards

**Comment by fit-alessandro-berti** [comment]
Dear joleaf,

You could run pm4py by deinstalling cvxopt (actually there are no binary distributions for M1)

In that case, the linear solve will fallback on "scipy" if available or "PuLP". They are significantly slower for some tasks (such as alignments) but all the other functionalities should work just fine.

You can check the linear solved used by PM4Py by doing: print(pm4py.util.lp.solver.DEFAULT_LP_SOLVER_VARIANT)

**Comment by joleaf** [comment]
Dear @fit-alessandro-berti , thank you so much!! It is working now :)

```
pip install pm4py
pip uninstall cvxopt
python -c "import pm4py"
```
..removes the error.
