### ISSUE TITLE
Error importing pm4py: packaging.version.InvalidVersion

### ISSUE THREAD

**Issue by joleaf** [process-intelligence-solutions/pm4py#365]
Hey, I got the following error after installation of PM4PY in a new python 3.11 virtualenv (mac M1):
Running `python` and just import `pm4py`:
```
Python 3.11.1 (v3.11.1:a7a450f84a, Dec  6 2022, 15:24:06) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pm4py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jonasblatt/pm4pytest/venv/lib/python3.11/site-packages/pm4py/__init__.py", line 20, in <module>
    from pm4py import analysis, conformance, convert, discovery, filtering, hof, ml, ocel, org, read, sim, stats, utils, vis, write
  File "/Users/jonasblatt/pm4pytest/venv/lib/python3.11/site-packages/pm4py/conformance.py", line 343, in <module>
    @deprecation.deprecated("2.3.0", "3.0.0", "conformance checking using footprints will not be exposed in a future release")
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jonasblatt/pm4pytest/venv/lib/python3.11/site-packages/deprecation.py", line 170, in deprecated
    current_version = version.parse(current_version)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jonasblatt/pm4pytest/venv/lib/python3.11/site-packages/packaging/version.py", line 52, in parse
    return Version(version)
           ^^^^^^^^^^^^^^^^
  File "/Users/jonasblatt/pm4pytest/venv/lib/python3.11/site-packages/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: 'conformance checking using footprints will not be exposed in a future release'
```

Did I miss something to install?

Edit:
Error only occurs in pm4py>=2.3.0, Version 2.2.32 works.

**Comment by joleaf** [comment]
Just saw the commit: https://github.com/pm4py/pm4py-core/commit/42cbe92e64f591a07771b03a7d45b4e46e1f9b29
which should resolve my issue. Thank you!
